using ShoppetApp.Models;
using ShoppetApp.Services;
namespace ShoppetApp.Pages;
public partial class VetVisitsPage:ContentPage
{
 readonly ApiService api;int editing;List<Pet> pets=new();
 public VetVisitsPage(ApiService api){InitializeComponent();this.api=api;Date.Date=DateTime.Today.AddDays(1);Time.Time=TimeSpan.FromHours(9);}
 protected override async void OnAppearing(){base.OnAppearing();try{pets=await api.GetPetsAsync();Pets.ItemsSource=pets;await Reload();}catch(Exception){await DisplayAlertAsync("Care unavailable","Check your connection and sign in again if needed.","OK");}}
 async Task Reload(){Rows.Children.Clear();foreach(var x in await api.GetVetVisitsAsync()){var name=pets.FirstOrDefault(p=>p.Id==x.PetId)?.Name??"Pet";var edit=new Button{Text="Edit",BackgroundColor=Color.FromArgb("#edf5f0"),TextColor=Color.FromArgb("#204d4c")};edit.Clicked+=(_,_)=>{editing=x.Id;Pets.SelectedItem=pets.FirstOrDefault(p=>p.Id==x.PetId);Clinic.Text=x.ClinicName;Date.Date=x.VisitAt.Date;Time.Time=x.VisitAt.TimeOfDay;Purpose.Text=x.Purpose;Notes.Text=x.Notes;Done.IsChecked=x.Completed;};var delete=new Button{Text="Delete",BackgroundColor=Colors.Transparent,TextColor=Color.FromArgb("#956144")};delete.Clicked+=async(_,_)=>{if(await DisplayAlertAsync("Delete reminder?",x.Purpose,"Delete","Cancel")){if(await api.DeleteVetVisitAsync(x.Id))await Reload();else await DisplayAlertAsync("Not deleted","Try again after checking your connection.","OK");}};Rows.Children.Add(new Border{BackgroundColor=Colors.White,Stroke=Color.FromArgb("#dde6de"),Padding=16,StrokeShape=new Microsoft.Maui.Controls.Shapes.RoundRectangle{CornerRadius=18},Content=new VerticalStackLayout{Spacing=8,Children={new Label{Text=$"{name} · {x.Purpose}",FontFamily="NunitoBold",TextColor=Color.FromArgb("#204d4c")},new Label{Text=x.Display},new Label{Text=x.Completed?"Completed":"Upcoming",TextColor=Color.FromArgb("#647c76")},new Label{Text=x.Notes},new HorizontalStackLayout{Spacing=12,Children={edit,delete}}}}});}}
 async void Save(object? sender,EventArgs e){if(Pets.SelectedItem is not Pet pet){await DisplayAlertAsync("Choose a pet","Select your pet for this reminder.","OK");return;}try{var x=new VetVisit{Id=editing,PetId=pet.Id,ClinicName=Clinic.Text??"",Purpose=Purpose.Text??"",Notes=Notes.Text??"",VisitAt=(Date.Date??DateTime.Today).Date.Add(Time.Time??TimeSpan.Zero),Completed=Done.IsChecked};if(await api.SaveVetVisitAsync(x)){ClearForm();await Reload();}else await DisplayAlertAsync("Not saved","Check reminder details and your connection.","OK");}catch(Exception){await DisplayAlertAsync("Not saved","Check your connection and try again.","OK");}}
 void Clear(object? sender,EventArgs e)=>ClearForm();void ClearForm(){editing=0;Pets.SelectedIndex=-1;Clinic.Text=Purpose.Text=Notes.Text="";Done.IsChecked=false;}
}
